SELECT * FROM posts LIMIT 25;

-- 
-- Postgres setup
-- 
CREATE TABLE posts (
	id SERIAL PRIMARY KEY NOT NULL,
	title TEXT NOT NULL,
	body TEXT NOT NULL,
	"createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO "posts" (title, body)
SELECT CONCAT('some post with a number ', num, ' for fun') AS title,
	   CONCAT ('hello this is my post about the number ', num) AS body
FROM generate_series(1,250) as num
;

-- 
-- MySQL setup
-- 
CREATE TABLE posts (
	id int NOT NULL AUTO_INCREMENT,
	title TINYTEXT NOT NULL,
	body TEXT NOT NULL,
	createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)	
);

-- How does MySQL not have a buitl-in way to generate a bunch of data?? Like Postgres has generate_series()
-- Planetscale (or Vitess?) doesn't support CTEs either let's just do it by hand...
INSERT INTO posts (title, body)
VALUES
    ("some post with a number 1 for fun", "hello this is my post about the number 1"),
    ("some post with a number 2 for fun", "hello this is my post about the number 2"),
    ("some post with a number 3 for fun", "hello this is my post about the number 3"),
    ("some post with a number 4 for fun", "hello this is my post about the number 4"),
    ("some post with a number 5 for fun", "hello this is my post about the number 5"),
    ("some post with a number 6 for fun", "hello this is my post about the number 6"),
    ("some post with a number 7 for fun", "hello this is my post about the number 7"),
    ("some post with a number 8 for fun", "hello this is my post about the number 8"),
    ("some post with a number 9 for fun", "hello this is my post about the number 9"),
    ("some post with a number 10 for fun", "hello this is my post about the number 10"),
    ("some post with a number 11 for fun", "hello this is my post about the number 11"),
    ("some post with a number 12 for fun", "hello this is my post about the number 12"),
    ("some post with a number 13 for fun", "hello this is my post about the number 13"),
    ("some post with a number 14 for fun", "hello this is my post about the number 14"),
    ("some post with a number 15 for fun", "hello this is my post about the number 15"),
    ("some post with a number 16 for fun", "hello this is my post about the number 16"),
    ("some post with a number 17 for fun", "hello this is my post about the number 17"),
    ("some post with a number 18 for fun", "hello this is my post about the number 18"),
    ("some post with a number 19 for fun", "hello this is my post about the number 19"),
    ("some post with a number 20 for fun", "hello this is my post about the number 20"),
    ("some post with a number 21 for fun", "hello this is my post about the number 21"),
    ("some post with a number 22 for fun", "hello this is my post about the number 22"),
    ("some post with a number 23 for fun", "hello this is my post about the number 23"),
    ("some post with a number 24 for fun", "hello this is my post about the number 24"),
    ("some post with a number 25 for fun", "hello this is my post about the number 25"),
    ("some post with a number 26 for fun", "hello this is my post about the number 26"),
    ("some post with a number 27 for fun", "hello this is my post about the number 27"),
    ("some post with a number 28 for fun", "hello this is my post about the number 28"),
    ("some post with a number 29 for fun", "hello this is my post about the number 29"),
    ("some post with a number 30 for fun", "hello this is my post about the number 30"),
    ("some post with a number 31 for fun", "hello this is my post about the number 31"),
    ("some post with a number 32 for fun", "hello this is my post about the number 32"),
    ("some post with a number 33 for fun", "hello this is my post about the number 33"),
    ("some post with a number 34 for fun", "hello this is my post about the number 34"),
    ("some post with a number 35 for fun", "hello this is my post about the number 35"),
    ("some post with a number 36 for fun", "hello this is my post about the number 36"),
    ("some post with a number 37 for fun", "hello this is my post about the number 37"),
    ("some post with a number 38 for fun", "hello this is my post about the number 38"),
    ("some post with a number 39 for fun", "hello this is my post about the number 39"),
    ("some post with a number 40 for fun", "hello this is my post about the number 40"),
    ("some post with a number 41 for fun", "hello this is my post about the number 41"),
    ("some post with a number 42 for fun", "hello this is my post about the number 42"),
    ("some post with a number 43 for fun", "hello this is my post about the number 43"),
    ("some post with a number 44 for fun", "hello this is my post about the number 44"),
    ("some post with a number 45 for fun", "hello this is my post about the number 45"),
    ("some post with a number 46 for fun", "hello this is my post about the number 46"),
    ("some post with a number 47 for fun", "hello this is my post about the number 47"),
    ("some post with a number 48 for fun", "hello this is my post about the number 48"),
    ("some post with a number 49 for fun", "hello this is my post about the number 49"),
    ("some post with a number 50 for fun", "hello this is my post about the number 50"),
    ("some post with a number 51 for fun", "hello this is my post about the number 51"),
    ("some post with a number 52 for fun", "hello this is my post about the number 52"),
    ("some post with a number 53 for fun", "hello this is my post about the number 53"),
    ("some post with a number 54 for fun", "hello this is my post about the number 54"),
    ("some post with a number 55 for fun", "hello this is my post about the number 55"),
    ("some post with a number 56 for fun", "hello this is my post about the number 56"),
    ("some post with a number 57 for fun", "hello this is my post about the number 57"),
    ("some post with a number 58 for fun", "hello this is my post about the number 58"),
    ("some post with a number 59 for fun", "hello this is my post about the number 59"),
    ("some post with a number 60 for fun", "hello this is my post about the number 60"),
    ("some post with a number 61 for fun", "hello this is my post about the number 61"),
    ("some post with a number 62 for fun", "hello this is my post about the number 62"),
    ("some post with a number 63 for fun", "hello this is my post about the number 63"),
    ("some post with a number 64 for fun", "hello this is my post about the number 64"),
    ("some post with a number 65 for fun", "hello this is my post about the number 65"),
    ("some post with a number 66 for fun", "hello this is my post about the number 66"),
    ("some post with a number 67 for fun", "hello this is my post about the number 67"),
    ("some post with a number 68 for fun", "hello this is my post about the number 68"),
    ("some post with a number 69 for fun", "hello this is my post about the number 69"),
    ("some post with a number 70 for fun", "hello this is my post about the number 70"),
    ("some post with a number 71 for fun", "hello this is my post about the number 71"),
    ("some post with a number 72 for fun", "hello this is my post about the number 72"),
    ("some post with a number 73 for fun", "hello this is my post about the number 73"),
    ("some post with a number 74 for fun", "hello this is my post about the number 74"),
    ("some post with a number 75 for fun", "hello this is my post about the number 75"),
    ("some post with a number 76 for fun", "hello this is my post about the number 76"),
    ("some post with a number 77 for fun", "hello this is my post about the number 77"),
    ("some post with a number 78 for fun", "hello this is my post about the number 78"),
    ("some post with a number 79 for fun", "hello this is my post about the number 79"),
    ("some post with a number 80 for fun", "hello this is my post about the number 80"),
    ("some post with a number 81 for fun", "hello this is my post about the number 81"),
    ("some post with a number 82 for fun", "hello this is my post about the number 82"),
    ("some post with a number 83 for fun", "hello this is my post about the number 83"),
    ("some post with a number 84 for fun", "hello this is my post about the number 84"),
    ("some post with a number 85 for fun", "hello this is my post about the number 85"),
    ("some post with a number 86 for fun", "hello this is my post about the number 86"),
    ("some post with a number 87 for fun", "hello this is my post about the number 87"),
    ("some post with a number 88 for fun", "hello this is my post about the number 88"),
    ("some post with a number 89 for fun", "hello this is my post about the number 89"),
    ("some post with a number 90 for fun", "hello this is my post about the number 90"),
    ("some post with a number 91 for fun", "hello this is my post about the number 91"),
    ("some post with a number 92 for fun", "hello this is my post about the number 92"),
    ("some post with a number 93 for fun", "hello this is my post about the number 93"),
    ("some post with a number 94 for fun", "hello this is my post about the number 94"),
    ("some post with a number 95 for fun", "hello this is my post about the number 95"),
    ("some post with a number 96 for fun", "hello this is my post about the number 96"),
    ("some post with a number 97 for fun", "hello this is my post about the number 97"),
    ("some post with a number 98 for fun", "hello this is my post about the number 98"),
    ("some post with a number 99 for fun", "hello this is my post about the number 99"),
    ("some post with a number 100 for fun", "hello this is my post about the number 100"),
    ("some post with a number 101 for fun", "hello this is my post about the number 101"),
    ("some post with a number 102 for fun", "hello this is my post about the number 102"),
    ("some post with a number 103 for fun", "hello this is my post about the number 103"),
    ("some post with a number 104 for fun", "hello this is my post about the number 104"),
    ("some post with a number 105 for fun", "hello this is my post about the number 105"),
    ("some post with a number 106 for fun", "hello this is my post about the number 106"),
    ("some post with a number 107 for fun", "hello this is my post about the number 107"),
    ("some post with a number 108 for fun", "hello this is my post about the number 108"),
    ("some post with a number 109 for fun", "hello this is my post about the number 109"),
    ("some post with a number 110 for fun", "hello this is my post about the number 110"),
    ("some post with a number 111 for fun", "hello this is my post about the number 111"),
    ("some post with a number 112 for fun", "hello this is my post about the number 112"),
    ("some post with a number 113 for fun", "hello this is my post about the number 113"),
    ("some post with a number 114 for fun", "hello this is my post about the number 114"),
    ("some post with a number 115 for fun", "hello this is my post about the number 115"),
    ("some post with a number 116 for fun", "hello this is my post about the number 116"),
    ("some post with a number 117 for fun", "hello this is my post about the number 117"),
    ("some post with a number 118 for fun", "hello this is my post about the number 118"),
    ("some post with a number 119 for fun", "hello this is my post about the number 119"),
    ("some post with a number 120 for fun", "hello this is my post about the number 120"),
    ("some post with a number 121 for fun", "hello this is my post about the number 121"),
    ("some post with a number 122 for fun", "hello this is my post about the number 122"),
    ("some post with a number 123 for fun", "hello this is my post about the number 123"),
    ("some post with a number 124 for fun", "hello this is my post about the number 124"),
    ("some post with a number 125 for fun", "hello this is my post about the number 125"),
    ("some post with a number 126 for fun", "hello this is my post about the number 126"),
    ("some post with a number 127 for fun", "hello this is my post about the number 127"),
    ("some post with a number 128 for fun", "hello this is my post about the number 128"),
    ("some post with a number 129 for fun", "hello this is my post about the number 129"),
    ("some post with a number 130 for fun", "hello this is my post about the number 130"),
    ("some post with a number 131 for fun", "hello this is my post about the number 131"),
    ("some post with a number 132 for fun", "hello this is my post about the number 132"),
    ("some post with a number 133 for fun", "hello this is my post about the number 133"),
    ("some post with a number 134 for fun", "hello this is my post about the number 134"),
    ("some post with a number 135 for fun", "hello this is my post about the number 135"),
    ("some post with a number 136 for fun", "hello this is my post about the number 136"),
    ("some post with a number 137 for fun", "hello this is my post about the number 137"),
    ("some post with a number 138 for fun", "hello this is my post about the number 138"),
    ("some post with a number 139 for fun", "hello this is my post about the number 139"),
    ("some post with a number 140 for fun", "hello this is my post about the number 140"),
    ("some post with a number 141 for fun", "hello this is my post about the number 141"),
    ("some post with a number 142 for fun", "hello this is my post about the number 142"),
    ("some post with a number 143 for fun", "hello this is my post about the number 143"),
    ("some post with a number 144 for fun", "hello this is my post about the number 144"),
    ("some post with a number 145 for fun", "hello this is my post about the number 145"),
    ("some post with a number 146 for fun", "hello this is my post about the number 146"),
    ("some post with a number 147 for fun", "hello this is my post about the number 147"),
    ("some post with a number 148 for fun", "hello this is my post about the number 148"),
    ("some post with a number 149 for fun", "hello this is my post about the number 149"),
    ("some post with a number 150 for fun", "hello this is my post about the number 150"),
    ("some post with a number 151 for fun", "hello this is my post about the number 151"),
    ("some post with a number 152 for fun", "hello this is my post about the number 152"),
    ("some post with a number 153 for fun", "hello this is my post about the number 153"),
    ("some post with a number 154 for fun", "hello this is my post about the number 154"),
    ("some post with a number 155 for fun", "hello this is my post about the number 155"),
    ("some post with a number 156 for fun", "hello this is my post about the number 156"),
    ("some post with a number 157 for fun", "hello this is my post about the number 157"),
    ("some post with a number 158 for fun", "hello this is my post about the number 158"),
    ("some post with a number 159 for fun", "hello this is my post about the number 159"),
    ("some post with a number 160 for fun", "hello this is my post about the number 160"),
    ("some post with a number 161 for fun", "hello this is my post about the number 161"),
    ("some post with a number 162 for fun", "hello this is my post about the number 162"),
    ("some post with a number 163 for fun", "hello this is my post about the number 163"),
    ("some post with a number 164 for fun", "hello this is my post about the number 164"),
    ("some post with a number 165 for fun", "hello this is my post about the number 165"),
    ("some post with a number 166 for fun", "hello this is my post about the number 166"),
    ("some post with a number 167 for fun", "hello this is my post about the number 167"),
    ("some post with a number 168 for fun", "hello this is my post about the number 168"),
    ("some post with a number 169 for fun", "hello this is my post about the number 169"),
    ("some post with a number 170 for fun", "hello this is my post about the number 170"),
    ("some post with a number 171 for fun", "hello this is my post about the number 171"),
    ("some post with a number 172 for fun", "hello this is my post about the number 172"),
    ("some post with a number 173 for fun", "hello this is my post about the number 173"),
    ("some post with a number 174 for fun", "hello this is my post about the number 174"),
    ("some post with a number 175 for fun", "hello this is my post about the number 175"),
    ("some post with a number 176 for fun", "hello this is my post about the number 176"),
    ("some post with a number 177 for fun", "hello this is my post about the number 177"),
    ("some post with a number 178 for fun", "hello this is my post about the number 178"),
    ("some post with a number 179 for fun", "hello this is my post about the number 179"),
    ("some post with a number 180 for fun", "hello this is my post about the number 180"),
    ("some post with a number 181 for fun", "hello this is my post about the number 181"),
    ("some post with a number 182 for fun", "hello this is my post about the number 182"),
    ("some post with a number 183 for fun", "hello this is my post about the number 183"),
    ("some post with a number 184 for fun", "hello this is my post about the number 184"),
    ("some post with a number 185 for fun", "hello this is my post about the number 185"),
    ("some post with a number 186 for fun", "hello this is my post about the number 186"),
    ("some post with a number 187 for fun", "hello this is my post about the number 187"),
    ("some post with a number 188 for fun", "hello this is my post about the number 188"),
    ("some post with a number 189 for fun", "hello this is my post about the number 189"),
    ("some post with a number 190 for fun", "hello this is my post about the number 190"),
    ("some post with a number 191 for fun", "hello this is my post about the number 191"),
    ("some post with a number 192 for fun", "hello this is my post about the number 192"),
    ("some post with a number 193 for fun", "hello this is my post about the number 193"),
    ("some post with a number 194 for fun", "hello this is my post about the number 194"),
    ("some post with a number 195 for fun", "hello this is my post about the number 195"),
    ("some post with a number 196 for fun", "hello this is my post about the number 196"),
    ("some post with a number 197 for fun", "hello this is my post about the number 197"),
    ("some post with a number 198 for fun", "hello this is my post about the number 198"),
    ("some post with a number 199 for fun", "hello this is my post about the number 199"),
    ("some post with a number 200 for fun", "hello this is my post about the number 200"),
    ("some post with a number 201 for fun", "hello this is my post about the number 201"),
    ("some post with a number 202 for fun", "hello this is my post about the number 202"),
    ("some post with a number 203 for fun", "hello this is my post about the number 203"),
    ("some post with a number 204 for fun", "hello this is my post about the number 204"),
    ("some post with a number 205 for fun", "hello this is my post about the number 205"),
    ("some post with a number 206 for fun", "hello this is my post about the number 206"),
    ("some post with a number 207 for fun", "hello this is my post about the number 207"),
    ("some post with a number 208 for fun", "hello this is my post about the number 208"),
    ("some post with a number 209 for fun", "hello this is my post about the number 209"),
    ("some post with a number 210 for fun", "hello this is my post about the number 210"),
    ("some post with a number 211 for fun", "hello this is my post about the number 211"),
    ("some post with a number 212 for fun", "hello this is my post about the number 212"),
    ("some post with a number 213 for fun", "hello this is my post about the number 213"),
    ("some post with a number 214 for fun", "hello this is my post about the number 214"),
    ("some post with a number 215 for fun", "hello this is my post about the number 215"),
    ("some post with a number 216 for fun", "hello this is my post about the number 216"),
    ("some post with a number 217 for fun", "hello this is my post about the number 217"),
    ("some post with a number 218 for fun", "hello this is my post about the number 218"),
    ("some post with a number 219 for fun", "hello this is my post about the number 219"),
    ("some post with a number 220 for fun", "hello this is my post about the number 220"),
    ("some post with a number 221 for fun", "hello this is my post about the number 221"),
    ("some post with a number 222 for fun", "hello this is my post about the number 222"),
    ("some post with a number 223 for fun", "hello this is my post about the number 223"),
    ("some post with a number 224 for fun", "hello this is my post about the number 224"),
    ("some post with a number 225 for fun", "hello this is my post about the number 225"),
    ("some post with a number 226 for fun", "hello this is my post about the number 226"),
    ("some post with a number 227 for fun", "hello this is my post about the number 227"),
    ("some post with a number 228 for fun", "hello this is my post about the number 228"),
    ("some post with a number 229 for fun", "hello this is my post about the number 229"),
    ("some post with a number 230 for fun", "hello this is my post about the number 230"),
    ("some post with a number 231 for fun", "hello this is my post about the number 231"),
    ("some post with a number 232 for fun", "hello this is my post about the number 232"),
    ("some post with a number 233 for fun", "hello this is my post about the number 233"),
    ("some post with a number 234 for fun", "hello this is my post about the number 234"),
    ("some post with a number 235 for fun", "hello this is my post about the number 235"),
    ("some post with a number 236 for fun", "hello this is my post about the number 236"),
    ("some post with a number 237 for fun", "hello this is my post about the number 237"),
    ("some post with a number 238 for fun", "hello this is my post about the number 238"),
    ("some post with a number 239 for fun", "hello this is my post about the number 239"),
    ("some post with a number 240 for fun", "hello this is my post about the number 240"),
    ("some post with a number 241 for fun", "hello this is my post about the number 241"),
    ("some post with a number 242 for fun", "hello this is my post about the number 242"),
    ("some post with a number 243 for fun", "hello this is my post about the number 243"),
    ("some post with a number 244 for fun", "hello this is my post about the number 244"),
    ("some post with a number 245 for fun", "hello this is my post about the number 245"),
    ("some post with a number 246 for fun", "hello this is my post about the number 246"),
    ("some post with a number 247 for fun", "hello this is my post about the number 247"),
    ("some post with a number 248 for fun", "hello this is my post about the number 248"),
    ("some post with a number 249 for fun", "hello this is my post about the number 249"),
    ("some post with a number 250 for fun", "hello this is my post about the number 250")
;

